spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/
    username: postgres
    password: 1111

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    jdbc:
      sqlony : off
      sqltiming : info
      resultsettable : info
      audit: off
      resultset : off
      connection: off
    org:
      springframework:
        transaction:
          interceptor: trace

inicis:
  apikey: ItEQKi3rY7uvDS8l
  mid: INIpayTest
  iv: HYb3yQ4f65QL89==
  approve:
    url: https://iniapi.inicis.com/api/v1/formpay
  refund:
    url: https://iniapi.inicis.com/api/v1/refund
